FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./
COPY turbo.json ./
COPY tsconfig.json ./

# Copy the entire workspace
COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npm run prisma:generate

# Build the application
RUN npm run build

# Expose the port your Next.js app runs on
EXPOSE 3000

# Update the start command to use next start directly
CMD ["npm", "run", "start-user-app"]
